lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: 86400
    # Set the user identity field
    user_identity_field: email
    # Set the handlers
    encoder:
        service: lexik_jwt_authentication.encoder.lcobucci
    token_extractors:
        authorization_header:
            enabled: true
            prefix: Bearer
            name: Authorization
    set_cookies:
        BEARER: ~
